# Generated by Django 4.2.2 on 2023-07-07 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_remove_contact_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="email",
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name="contact",
            name="name",
            field=models.CharField(max_length=120),
        ),
    ]
